#!/usr/bin/python
import os,sys,time,marshal
os.system('clear')

# Logo of this script
logo="""\a\a\33[32m
 (   (         *                              
 )\ ))\ )    (  `       (    (      (         
(()/(()/((   )\))(    ( )\   )\   ( )\    (   
 /(_))(_))\ ((_)()\   )((_|(((_)( )((_)   )\  
(_))(_))((_)(_()((_) ((_)_ )\ _ )((_)_ _ ((_) 
| _ \ _ \ __|  \/  |  | _ )(_)_\(_) _ ) | | | 
|  _/   / _|| |\/| |  | _ \ / _ \ | _ \ |_| | 
|_| |_|_\___|_|  |_|  |___//_/ \_\|___/\___/                                                

\33[34m_________________________________________________________________
\33[0;1m                      WELCOME TO PREM PROJECT
\33[34m_________________________________________________________________
 \33[31;1m          NAME >> MR PREM BABU | YOUTUBE >> PREM PROJECT \33[36;1m

[1] ENCRYPT BASH
[2] DECRYPT BASH
[3] ENCRYPT MARSHAL
[4] ABOUT PREM PROJECT
[5] EXIT
\33[0m"""

# About this script
about="""\33[32;1m
CODED BY MR PREM BABU

facebook.com/prembabu001

THIS SCRIPT IS WRITTEN IN PYTHON,
YOU CAN USE THIS SCRIPT TO ENCRYPT/DECRYPT YOUR BASH SCRIPTS
AND YOU CAN ALSO ENCRYPT PYTHON CODE IN MARSHAL
JUST TYPE PREM-DECOMPILED TO RUN THIS SCRIPT

THANKYOU FOR USING PREM PROJECT TOOL
CODER BY >> PREM PROJECT
YOUTUBE  >> PREM PROJECT
FACEBOOK >> facebook.com/prembabu01
\33[0m"""
print(logo)

# taking input from user
choice=input("SELECT >>> ")

# Encrypt bash
def encbash():
    in_file=input("ENTER FILE NAME >>> ")
    if not os.path.exists(in_file):
        print("error,file not found")
        encbash()
    os.system("bash-obfuscate "+in_file+" -o .temp")
    out_file=input('ENTER OUTPUT FILE NAME >>> ')
    with open(".temp","r") as temp_f, open(out_file,'w') as out_f:
        encdata=temp_f.read()
        out_f.write("# ENCRYPTION BY MR PREM PROJECT\n#FACEBOOK :- facebook.com/prembabu001\n\n"+encdata)
    os.remove(".temp")
    print("SUCCESSFUL PREM PROJECT "+[ in_file ]+" AND SAVED AS "+[ out_file ])

# Decrypt Bash
def decbash():
    in_file=input("ENTER FILE NAME >>> ")
    if not os.path.exists(in_file):
        print("error,file not found")
        decbash()
    with open(in_file,'r') as in_f, open(".temp1",'w') as temp_f:
        filedata = in_f.read()
        if not (filedata.find("eval") != -1):
            print("error can not be decrypted")
            exit()
        newdata = filedata.replace("eval","echo")
        temp_f.write(newdata)
    out_file=input("ENTER OUTPUT FILE NAME >>> ")
    os.system("bash .temp1 > .temp2")
    os.remove(".temp1")
    with open(".temp2",'r') as temp_f2, open(out_file,'w') as out_f:
        filedata = temp_f2.read()
        out_f.write("#DECRYPTION BY MR PREM PROJECT\n#FACEBOOK :- facebook.com/prembabu001\n\n"+filedata)
    os.remove(".temp2")
    print("SUCCESSFUL PREM PROJECT "+[ in_file ]+" AND SAVED AS "+[ out_file ])

# Encrypt python in marshal
def encpy():
    try:
        file = input('ENTER FILE NAME >>> ')
        As = file.replace('.py', '')
    except KeyboardInterrupt:
        sys.exit()
    else:
        try:
            strng = open(file, 'r').read()
        except IOError:
            print('No such file')
            sys.exit()
        try:
            code = compile(strng,'','exec')
            data = marshal.dumps(code)
        except TypeError:
            print("FILE ALLREADY ENCRYPTED")
    fileout = open(As + '_en.py', 'w')
    fileout.write('#ENCRYPTED BY MR PREM PROJECT\n')
    fileout.write('#FACEBOOK :- facebook.com/prembabu001\n')
    fileout.write('import marshal\n')
    fileout.write('exec(marshal.loads(' + repr(data) + '))')
    fileout.close()
    time.sleep(3)
    print ('SUCCECSFULL PREM PROJECT' + As + '_en.py')

# Choses
if choice=='1':
    encbash()
elif choice=='2':
    decbash()
elif choice=='3':
    encpy()
elif choice=='5':
    print("THANKYOU FOR USING PREM PROJECT TOOL")
    time.sleep(1)
    sys.exit()
elif choice=='4':
    print(about)
else:
    print("WRONG INPUT PLEASE TRY AGAIN")
    time.sleep(2)
    os.system("PREM-DECOMPILED")
